
CREATE TABLE `MEMBER` (
  `MEMBER_ID` varchar(15) NOT NULL,
  `GRADE_ID` int NOT NULL,
  `MEMBER_PASSWORD` varchar(15) NOT NULL,
  `MEMBER_NAME` varchar(60) NOT NULL,
  `DAY_OF_BIRTH` date NOT NULL,
  `GENDER` varchar(10) NOT NULL,
  `PHONE_NUMBER` varchar(11) NOT NULL,
  `EMAIL` varchar(255) NOT NULL,
  `AUTHORITY` varchar(7) NOT NULL,
  `MEMBER_STATE` varchar(7) NOT NULL,
  PRIMARY KEY (`MEMBER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `PRODUCT` (
  `PRODUCT_ID` int NOT NULL AUTO_INCREMENT,
  `PRODUCT_NAME` varchar(60) NOT NULL,
  `PRODUCT_DETAIL` varchar(500) NOT NULL,
  `COST_PRICE` int NOT NULL,
  `RETAIL_PRICE` int NOT NULL,
  `SALE_PRICE` int NOT NULL,
  `STOCK` int NOT NULL,
  `INGREDIENT` varchar(60) NOT NULL,
  `USAGE` varchar(75) NOT NULL,
  `EXPIRATION_DATE` varchar(75) NOT NULL,
  `REGISTER_DATE` datetime NOT NULL,
  `MODIFY_DATE` datetime NOT NULL,
  `SALE_STATE` varchar(15) NOT NULL,
  PRIMARY KEY (`PRODUCT_ID`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE `MONTHLY_SALES_STATS` (
  `MONTHLY_SALES_STATS_ID` INT NOT NULL AUTO_INCREMENT,
  `MONTHLY_TOTAL_CALCULATE_DATE` DATE NOT NULL,
  `MONTHLY_TOTAL_GROSS_MARGINE` INT NOT NULL,
  `MONTHLY_TOTAL_NET_PROFIT` INT NOT NULL,
  PRIMARY KEY (`MONTHLY_SALES_STATS_ID`)
  )ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

CREATE TABLE `IAMGE` (
  `IMAGE_ID` INT NOT NULL AUTO_INCREMENT,
  `IMAGE_PATH` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`IMAGE_ID`)
  )ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

CREATE TABLE `BUY_INFO` (
  `BUY_INFO_ID` int NOT NULL,
  `MEMBER_ID` varchar(15) NOT NULL,
  `BUY_DATE` datetime NOT NULL,
  `DELIVERY_POSTCODE` int NOT NULL,
  `DELIVERY_ADDRESS` varchar(255) NOT NULL,
  `DELIVERY_DETAIL_ADDRESS` varchar(255) NOT NULL,
  `ORDER_STATE` varchar(12) NOT NULL,
  PRIMARY KEY (`BUY_INFO_ID`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE `MONTHLY_PRODUCT_SALES_STATS` (
  `MONTHLY_PRODUCT_SALES_STATS_ID` INT NOT NULL AUTO_INCREMENT,
  `PRODUCT_ID` INT NOT NULL,
  `MONTHLY_TOTAL_CALCULATE_DATE` DATE NOT NULL,
  `MONTHLY_TOTAL_QUANTITY` INT NOT NULL,
  `MONTHLY_TOTAL_GROSS_MARGINE` INT NOT NULL,
  `MONTHLY_TOTAL_NET_PROFIT` INT NOT NULL,
  PRIMARY KEY (`MONTHLY_PRODUCT_SALES_STATS_ID`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

CREATE TABLE `PRODUCT_CATEGORY` (
  `PRODUCT_CATEGORY_ID` INT NOT NULL AUTO_INCREMENT,
  `PRODUCT_ID` INT NOT NULL,
  `CATEGORY_ID` INT NOT NULL,
  PRIMARY KEY (`PRODUCT_CATEGORY_ID`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

CREATE TABLE `KAKAO_MEMBER` (
  `KAKAO_ID` VARCHAR(255) NOT NULL,
  `MEMBER_ID` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`KAKAO_ID`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

CREATE TABLE `MEMBER_COUPON` (
  `MEMBER_COUPON_ID` INT NOT NULL AUTO_INCREMENT,
  `MEMBER_ID` VARCHAR(15) NOT NULL,
  `COUPON_ID` INT NOT NULL,
  `USAGE` INT NOT NULL,
  PRIMARY KEY (`MEMBER_COUPON_ID`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

CREATE TABLE `CART` (
  `CART_ID` INT NOT NULL AUTO_INCREMENT,
  `MEMBER_ID` VARCHAR(15) NOT NULL,
  `PRODUCT_ID` INT NOT NULL,
  `PRODUCT_QUANTITY` INT NOT NULL,
  PRIMARY KEY (`CART_ID`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

CREATE TABLE `ORDER` (
  `ORDER_ID` INT NOT NULL AUTO_INCREMENT,
  `BUY_INFO_ID` INT NOT NULL,
  `PRODUCT_ID` INT NOT NULL,
  `MEMBER_COUPON_ID` INT NOT NULL,
  `BUY_QUANTITY` INT NOT NULL,
  `PAYMENT_PRICE` INT NOT NULL,
  `HAS_REVIEW` INT NOT NULL,
  PRIMARY KEY (`ORDER_ID`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

CREATE TABLE `PRODUCT_IMAGE` (
  `PRODUCT_IMAGE_ID` INT NOT NULL AUTO_INCREMENT,
  `IMAGE_ID` INT NOT NULL,
  `PRODUCT_ID` INT NOT NULL,
  PRIMARY KEY (`PRODUCT_IMAGE_ID`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

CREATE TABLE `REVIEW_IMAGE` (
  `REVIEW_IMAGE_ID` INT NOT NULL AUTO_INCREMENT,
  `IMAGE_ID` INT NOT NULL,
  `REVIEW_ID` INT NOT NULL,
  PRIMARY KEY (`REVIEW_IMAGE_ID`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

CREATE TABLE `REVIEW` (
  `REVIEW_ID` INT NOT NULL AUTO_INCREMENT,
  `BUY_INFO_ID` INT NOT NULL,
  `SCORE` INT NOT NULL,
  `CONTENT` VARCHAR(1500) NOT NULL,
  `WRITE_DATE` DATETIME NOT NULL,
  PRIMARY KEY (`REVIEW_ID`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4;

CREATE TABLE `DAILY_SALES_STATS` (
  `DAILY_SALES_STATS_ID` int NOT NULL,
  `DAILY_TOTAL_CALCULATE_DATE` date NOT NULL,
  `DAILY_TOTAL_GROSS_MARGINE` int NOT NULL,
  `DAILY_TOTAL_NET_PROFIT` int NOT NULL,
  PRIMARY KEY (`DAILY_SALES_STATS_ID`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE `DAILY_PRODUCT_SALES_STATS` (
  `DAILY_PRODUCT_SALES_STATS_ID` int NOT NULL,
  `PRODUCT_ID` int NOT NULL,
  `DAILY_TOTAL_CALCULATE_DATE` date NOT NULL,
  `DAILY_TOTAL_QUANTITY` int NOT NULL,
  `DAILY_TOTAL_GROSS_MARGINE` int NOT NULL,
  `DAILY_TOTAL_NET_PROFIT` int NOT NULL,
  PRIMARY KEY (`DAILY_PRODUCT_SALES_STATS_ID`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE `PROVISION_BATCH_COUPON` (
  `PROVISION_BATCH_COUPON_ID` int NOT NULL,
  `COUPON_ID` int NOT NULL,
  `DEPLOY_STATUS` varchar(9) NOT NULL,
  PRIMARY KEY (`PROVISION_BATCH_COUPON_ID`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE `PROVISION_DOWNLOAD_COUPON` (
  `PROVISION_DOWNLOAD_COUPON_ID` int NOT NULL,
  `COUPON_ID` int NOT NULL,
  `IMAGE_ID` int NOT NULL,
  `DEPLOY_DEADLINE` datetime NOT NULL,
  `DEPLOY_STATUS` varchar(9) NOT NULL,
  PRIMARY KEY (`PROVISION_DOWNLOAD_COUPON_ID`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE `PROVISION_GRADE_COUPON` (
  `PROVISION_GRADE_COUPON_ID` int NOT NULL,
  `GRADE_ID` int NOT NULL,
  `COUPON_ID` int NOT NULL,
  `DEPLOY_CYCLE` varchar(5) NOT NULL,
  `DEPLOY_BASE` varchar(3) NOT NULL,
  PRIMARY KEY (`PROVISION_GRADE_COUPON_ID`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE `COUPON` (
  `COUPON_ID` int NOT NULL,
  `COUPON_NAME` varchar(75) NOT NULL,
  `CREATE_DATE` datetime NOT NULL,
  `DISTRIBUTE_DATE` datetime DEFAULT NULL,
  `EXPIRATION_DATE` datetime NOT NULL,
  `COUPON_TYPE` varchar(10) NOT NULL,
  PRIMARY KEY (`COUPON_ID`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE `COUPON_CATEGORY` (
  `COUPON_CATEGORY_ID` int NOT NULL,
  `COUPON_ID` int NOT NULL,
  `COUPON_CCATEGORY_IDATEGORYcol` int NOT NULL,
  PRIMARY KEY (`COUPON_CATEGORY_ID`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE `CATEGORY` (
  `CATEGORY_ID` int NOT NULL,
  `CATEGORY_NAME` varchar(15) NOT NULL,
  PRIMARY KEY (`CATEGORY_ID`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE `MEMBER_CATEGORY` (
  `MEMBER_CATEGORY_ID` int NOT NULL,
  `CATEGORY_ID` int NOT NULL,
  `MEMBER_ID` varchar(15) NOT NULL,
  PRIMARY KEY (`MEMBER_CATEGORY_ID`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE `PERCENTAGE_COUPON` (
  `PERCENTAGE_COUPON_ID` int NOT NULL,
  `COUPON_ID` int NOT NULL,
  `COUPON_DISCOUNT_RATE` int NOT NULL,
  `MAX_DISCOUNT_AMOUNT` int NOT NULL,
  PRIMARY KEY (`PERCENTAGE_COUPON_ID`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE `WON_COUPON` (
  `WON_COUPON_ID` int NOT NULL,
  `COUPON_ID` int NOT NULL,
  `COUPON_DISCOUNT_AMOUNT` int NOT NULL,
  `MIN_ORDER_AMOUNT` int NOT NULL,
  PRIMARY KEY (`WON_COUPON_ID`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE `GRADE` (
  `GRADE_ID` int NOT NULL,
  `GRADE_NAME` varchar(30) NOT NULL,
  `LOWER_LIMIT` int NOT NULL,
  `UPPER_LIMIT` int NOT NULL,
  PRIMARY KEY (`GRADE_ID`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE `SHIPPING_ADDRESS` (
  `SHIPPING_ADDRESS_ID` int NOT NULL,
  `MEMBER_ID` varchar(15) NOT NULL,
  `PRIMARY` int NOT NULL,
  `SHIPPING_ADDRESS_NAME` varchar(30) NOT NULL,
  `SHIPPING_POSTCODE` int NOT NULL,
  `SHIPPING_ADDRESS` varchar(255) NOT NULL,
  `SHIPPING_DETAIL_ADDRESS` varchar(255) NOT NULL,
  PRIMARY KEY (`SHIPPING_ADDRESS_ID`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;


